const CATALOG='https://asoc.local/a2ui/catalogs/dashboard/v1';
const COMPONENTS=['Column','Row','Heading','Text','MetricGroup','Workflow','Breakdown','Trend','RecordList','RestrictedSummary'];
const METRICS=['operations_flow','sla_summary','attention_tickets','restricted_incidents','incident_summary','incident_tasks','incident_activity'];
function artifact(app,dashboard){const id=dashboard.getString('active_artifact_id');return id?app.findRecordById('dashboard_artifacts',id):null;}
function validate(messages,bindings,scope){
  if(!Array.isArray(messages)||messages.length<2||messages.length>8)throw new BadRequestError('A2UI artifact must contain 2-8 messages.');
  if(!Array.isArray(bindings)||bindings.length<1||bindings.length>12)throw new BadRequestError('Dashboard requires 1-12 query bindings.');
  const ids={};for(const binding of bindings){if(!binding||typeof binding.id!=='string'||ids[binding.id]||!METRICS.includes(binding.metric))throw new BadRequestError('Invalid or duplicate dashboard query binding.');if(scope==='incident'&&!['incident_summary','incident_tasks','incident_activity'].includes(binding.metric))throw new BadRequestError('Incident dashboards may only use incident-scoped queries.');if(scope==='operations'&&['incident_summary','incident_tasks','incident_activity'].includes(binding.metric))throw new BadRequestError('Operations dashboards may not use incident-scoped queries.');if(binding.limit!==undefined&&(Number(binding.limit)<1||Number(binding.limit)>25))throw new BadRequestError('Dashboard query limit must be 1-25.');ids[binding.id]=true;}
  let created=false,updated=false,root=false;for(const message of messages){if(!message||message.version!=='v0.9')throw new BadRequestError('Only A2UI v0.9 messages are supported.');if(message.createSurface){if(created||message.createSurface.catalogId!==CATALOG)throw new BadRequestError('Invalid dashboard surface.');created=true;}else if(message.updateComponents){updated=true;const components=message.updateComponents.components;if(!Array.isArray(components)||components.length>30)throw new BadRequestError('Dashboard component list is invalid.');const componentIds={};for(const item of components){if(!item||typeof item.id!=='string'||componentIds[item.id]||!COMPONENTS.includes(item.component))throw new BadRequestError('Dashboard contains an unsupported component.');componentIds[item.id]=true;if(item.id==='root')root=true;if(item.binding&&!ids[item.binding])throw new BadRequestError('Dashboard component has an unknown binding.');if(item.children&&(!Array.isArray(item.children)||item.children.length>20))throw new BadRequestError('Invalid dashboard child list.');}for(const item of components)for(const child of item.children||[])if(!componentIds[child])throw new BadRequestError('Dashboard references a missing component.');}else throw new BadRequestError('Unsupported A2UI dashboard message.');}if(!created||!updated||!root)throw new BadRequestError('Dashboard requires createSurface and updateComponents messages with a root component.');
}
function data(app,user,dashboard,bindings,filters){
  const p=require(__hooks+'/platform.js');const nowMs=Date.now(),days=Math.min(90,Math.max(1,Number(filters.days)||7)),sinceMs=nowMs-days*86400000,severity=String(filters.severity||'');const all=app.findRecordsByFilter('incidents','','',0,0),accessible=all.filter(r=>p.canAccessIncident(app,user,r)),selected=accessible.filter(r=>!severity||r.getString('severity')===severity),ids={};accessible.forEach(r=>ids[r.getString('external_id')]=true);const results={};const inPeriod=value=>{const time=Date.parse(value||'');return Number.isFinite(time)&&time>=sinceMs&&time<=nowMs;};
  for(const binding of bindings){const limit=Math.min(25,Math.max(1,Number(binding.limit)||10));if(binding.metric==='restricted_incidents'){const hidden=all.filter(r=>!p.canAccessIncident(app,user,r)),by={SEV1:0,SEV2:0,SEV3:0,SEV4:0,unknown:0};hidden.forEach(r=>{const key=r.getString('severity');by[key]===undefined?by.unknown++:by[key]++;});results[binding.id]={total:hidden.length,by_severity:by,fixed_scope:'All current tenant incidents'};
    }else if(binding.metric==='operations_flow'){const intakes=app.findRecordsByFilter('intakes','','',0,0).filter(r=>inPeriod(r.getString('received_at'))),decisions=app.findRecordsByFilter('intake_decisions','','',0,0).filter(r=>inPeriod(r.getString('decided_at'))&&(!r.getString('incident_id')||ids[r.getString('incident_id')])),outcomes={create:0,comment:0,ignore:0};decisions.forEach(r=>{const key=r.getString('outcome');if(outcomes[key]!==undefined)outcomes[key]++;});const runs=app.findRecordsByFilter('tasks','','',0,0).filter(r=>ids[r.getString('incident_id')]&&r.getString('role_type')!=='chat'&&r.getString('template_id')!=='TPL-DASHBOARD'&&inPeriod(r.getString('finished_at')));results[binding.id]={period_days:days,intakes_received:intakes.length,triage_decisions:decisions.length,triage_outcomes:outcomes,response_runs_completed:runs.length,incidents_closed:selected.filter(r=>inPeriod(r.getString('closed_at'))).length,current_active:selected.filter(r=>!r.getString('closed_at')&&r.getString('status')!=='closed').length};
    }else if(binding.metric==='sla_summary'){const policies=app.findRecordsByFilter('sla_policies','enabled = true','-version',1);if(!policies.length){results[binding.id]={configured:false};continue;}const policy=policies[0],targets=p.json(policy,'targets')||{};let breached=0,dueSoon=0,eligible=0,met=0;for(const incident of selected){const target=Number((targets[incident.getString('severity')]||{}).closure_hours);if(!target)continue;eligible++;const elapsed=(Date.parse(incident.getString('closed_at')||new Date().toISOString())-Date.parse(incident.getString('opened_at')))/3600000;if(incident.getString('closed_at')){if(elapsed<=target)met++;}else if(elapsed>target)breached++;else if(elapsed>=target*(Number(policy.getFloat('due_soon_percent'))||80)/100)dueSoon++;}results[binding.id]={configured:true,policy:policy.getString('name'),version:policy.getInt('version'),active_breached:breached,active_due_soon:dueSoon,eligible,met,compliance_percent:eligible?Math.round(met*1000/eligible)/10:null};
    }else if(binding.metric==='attention_tickets'){const failed={};app.findRecordsByFilter('tasks','status = "failed" || status = "timed_out"','-finished_at',0,0).forEach(r=>failed[r.getString('incident_id')]=true);results[binding.id]=selected.filter(r=>!r.getString('closed_at')&&r.getString('status')!=='closed').sort((a,b)=>a.getString('severity').localeCompare(b.getString('severity'))).slice(0,limit).map(r=>({id:r.getString('external_id'),title:r.getString('title'),severity:r.getString('severity'),status:r.getString('status'),opened_at:r.getString('opened_at'),failed_run:!!failed[r.getString('external_id')]}));
    }else{const incidentId=dashboard.getString('incident_id'),incident=p.incidentForUser(app,user,incidentId);if(binding.metric==='incident_summary')results[binding.id]={id:incidentId,title:incident.getString('title'),severity:incident.getString('severity'),status:incident.getString('status'),owner:incident.getString('owner'),opened_at:incident.getString('opened_at'),closed_at:incident.getString('closed_at')};if(binding.metric==='incident_tasks')results[binding.id]=app.findRecordsByFilter('tasks','incident_id = {:id}','-created',limit,0,{id:incidentId}).map(r=>({id:r.getString('external_id'),title:r.getString('title'),status:r.getString('status'),role:r.getString('role_type'),finished_at:r.getString('finished_at')}));if(binding.metric==='incident_activity')results[binding.id]=app.findRecordsByFilter('incident_comments','incident_id = {:id}','-created_at',limit,0,{id:incidentId}).map(r=>({body:r.getString('body'),created_at:r.getString('created_at')}));}}
  return {generated_at:new Date().toISOString(),filters:{days,severity},results};
}
function queue(app,user,dashboard,instructions,force){const p=require(__hooks+'/platform.js'),template=p.find(app,'templates','external_id',dashboard.getString('playbook_id')),revision=dashboard.getInt('config_revision')||1,key=dashboard.id+':'+revision+':'+template.getInt('version')+(force?':'+$security.randomString(12):'');const existing=app.findRecordsByFilter('dashboard_generation_requests','generation_key = {:key}','',1,0,{key});if(existing.length)return existing[0];const request=p.make(app,'dashboard_generation_requests',{dashboard_id:dashboard.id,requester_id:user.id,target_revision:revision,playbook_version:template.getInt('version'),generation_key:key,status:'queued',instructions:instructions||dashboard.getString('instructions'),created_at:p.now()}),task=p.queue(app,{title:'Generate dashboard: '+dashboard.getString('name'),template_id:dashboard.getString('playbook_id'),profile_id:'profile-dashboard',incident_id:dashboard.getString('incident_id'),context_refs_json:{dashboard_id:dashboard.id,generation_request_id:request.id,requester_id:user.id,incident_id:dashboard.getString('incident_id'),instructions:request.getString('instructions')}},user.id);request.set('task_id',task.id);app.save(request);dashboard.set('last_generation_status','queued');dashboard.set('last_generation_task_id',task.id);dashboard.set('last_error','');app.save(dashboard);return request;}
function response(app,user,dashboard){const p=require(__hooks+'/platform.js');if(dashboard.getString('scope')==='incident')p.incidentForUser(app,user,dashboard.getString('incident_id'));const currentArtifact=artifact(app,dashboard),template=p.find(app,'templates','external_id',dashboard.getString('playbook_id'));if(!currentArtifact||currentArtifact.getInt('config_revision')!==dashboard.getInt('config_revision')||currentArtifact.getInt('playbook_version')!==template.getInt('version'))queue(app,user,dashboard,'',false);const current=artifact(app,dashboard);return {dashboard:{id:dashboard.id,external_id:dashboard.getString('external_id'),name:dashboard.getString('name'),scope:dashboard.getString('scope'),incident_id:dashboard.getString('incident_id'),instructions:dashboard.getString('instructions'),config_revision:dashboard.getInt('config_revision'),last_generation_status:dashboard.getString('last_generation_status'),last_error:dashboard.getString('last_error'),generated_at:dashboard.getString('generated_at')},artifact:current?{id:current.id,protocol_version:current.getString('protocol_version'),catalog_id:current.getString('catalog_id'),a2ui_messages:p.json(current,'a2ui_messages'),query_bindings:p.json(current,'query_bindings'),generated_at:current.getString('generated_at')}:null};}
module.exports={CATALOG,COMPONENTS,METRICS,artifact,validate,data,queue,response};
