<script lang="ts">
 import {onMount,createEventDispatcher} from 'svelte';
 import {currentUser,listUsers,inviteUser,updateUser,listRunners,listIntakes,listIntakeConfigs,createManualIntake,listPendingApprovals,approveTool,listTemplates,createTask,cancelTask,saveModelDefaults,listArtifacts,saveIntakeConfig,savePlaybookDefinition,type TaskRecord} from '../lib/pocketbase';
 export let tasks:TaskRecord[]=[];
 const dispatch=createEventDispatcher<{refresh:void}>();
 let open=false,section='health',error='',users:any[]=[],runners:any[]=[],intakes:any[]=[],configs:any[]=[],approvals:any[]=[],templates:any[]=[];
 let email='',role='analyst',provider='gemini',model='gemini-3.6-flash',intakeConfig='',intakeText='',taskTitle='',taskIncident='',taskTemplate='',filter='';
 let integrationName='',integrationKind='github',integrationPlaybook='TPL-TRIAGE',integrationConfig='{"repositories":[],"secret_env":"GITHUB_WEBHOOK_SECRET","token_env":"GITHUB_TOKEN"}';
 let editPlaybook='',playbookDefinition='';
 $: shown=tasks.filter(t=>`${t.status} ${t.incident_id} ${t.claimed_by_runner_id} ${t.role_type} ${t.template_id}`.toLowerCase().includes(filter.toLowerCase()));
 async function load(){try{[runners,intakes,configs,approvals,templates]=await Promise.all([listRunners(),listIntakes(),listIntakeConfigs(),listPendingApprovals(),listTemplates()]);if(currentUser()?.role==='admin')users=await listUsers();if(!intakeConfig)intakeConfig=configs.find(c=>c.kind==='manual')?.id||'';if(!taskTemplate)taskTemplate=templates.find(t=>t.role_type==='analysis')?.external_id||'';if(!editPlaybook&&templates[0]){editPlaybook=templates[0].id;playbookDefinition=JSON.stringify(templates[0].definition,null,2);}}catch(e){error=e instanceof Error?e.message:'Settings could not load';}}
 function selectPlaybook(){playbookDefinition=JSON.stringify(templates.find(t=>t.id===editPlaybook)?.definition||{},null,2);}
 async function act(fn:()=>Promise<any>){error='';try{await fn();await load();dispatch('refresh');}catch(e){error=e instanceof Error?e.message:'Action failed';}}
 function download(task:TaskRecord){act(async()=>{const data=await listArtifacts(task.id);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=(task.external_id||task.id)+'-artifacts.json';a.click();URL.revokeObjectURL(url);});}
 onMount(load);
</script>
<button class="toggle" on:click={()=>open=!open}>Control center{approvals.length?` · ${approvals.length}`:''}</button>
{#if open}<aside><nav>{#each ['health','tasks','intakes','approvals','settings'] as item}<button class:active={section===item} on:click={()=>section=item}>{item}</button>{/each}</nav>{#if error}<p class="error">{error}</p>{/if}
{#if section==='health'}<h2>Runtime health</h2><dl><dt>PocketBase</dt><dd class="ok">Connected</dd><dt>AI configuration</dt><dd>{runners[0]?.capabilities_json?.api_key_configured?'Key configured':'No key reported'}</dd></dl>{#each runners as r}<article><strong>{r.display_name}</strong><span>{r.status} · {r.capabilities_json?.launch_mode} · {r.capabilities_json?.ai_provider}/{r.capabilities_json?.ai_model}</span></article>{:else}<p>No active runner. Tasks will remain queued.</p>{/each}
{:else if section==='tasks'}<h2>Create and inspect tasks</h2><input placeholder="Filter status, incident, runner, role, playbook" bind:value={filter}/>{#if currentUser()?.role!=='read-only'}<input placeholder="Task title" bind:value={taskTitle}/><input placeholder="Incident ID (optional)" bind:value={taskIncident}/><select bind:value={taskTemplate}>{#each templates as t}<option value={t.external_id}>{t.name}</option>{/each}</select><button on:click={()=>act(()=>createTask({title:taskTitle,incident_id:taskIncident,template_id:taskTemplate}))}>Queue task</button>{/if}{#each shown as t}<article><strong>{t.title}</strong><span>{t.status} · {t.template_id} · {t.ai_provider||'pending'}/{t.ai_model||'pending'}</span><button on:click={()=>download(t)}>Download transcript/artifacts</button>{#if currentUser()?.role!=='read-only' && ['queued','claimed','running'].includes(t.status||'')}<button on:click={()=>act(()=>cancelTask(t.id))}>Cancel</button>{/if}</article>{/each}
{:else if section==='intakes'}<h2>Intake review</h2>{#if currentUser()?.role!=='read-only'}<select bind:value={intakeConfig}>{#each configs.filter(c=>c.kind==='manual') as c}<option value={c.id}>{c.name}</option>{/each}</select><textarea placeholder="Report or alert details" bind:value={intakeText}></textarea><button on:click={()=>act(()=>createManualIntake(intakeConfig,{text:intakeText}))}>Submit intake</button>{/if}{#each intakes as i}<article><strong>{i.source_key||i.id}</strong><span>{i.status} · revision {i.revision||'n/a'}</span></article>{/each}
{:else if section==='approvals'}<h2>Tool approvals</h2>{#each approvals as a}<article><strong>{a.tool}</strong><pre>{JSON.stringify(a.arguments,null,2)}</pre>{#if currentUser()?.role!=='read-only'}<button on:click={()=>act(()=>approveTool(a.id,true))}>Approve for task/session</button><button on:click={()=>act(()=>approveTool(a.id,false))}>Deny</button>{/if}</article>{:else}<p>No actions need approval.</p>{/each}
{:else}<h2>Settings</h2>{#if currentUser()?.role==='admin'}<h3>Model defaults</h3><select bind:value={provider}><option>gemini</option><option>openai</option><option>openai-compatible</option><option>ollama</option><option>mock</option></select><input bind:value={model}/><button on:click={()=>act(()=>saveModelDefaults(provider,model))}>Save non-secret defaults</button><p>API keys stay in runner environment secrets.</p><h3>Playbook policy</h3><select bind:value={editPlaybook} on:change={selectPlaybook}>{#each templates as t}<option value={t.id}>{t.name} · v{t.version}</option>{/each}</select><textarea bind:value={playbookDefinition}></textarea><button on:click={()=>act(()=>savePlaybookDefinition(editPlaybook,JSON.parse(playbookDefinition)))}>Validate and save policy</button><h3>Integrations and intakes</h3><input placeholder="Integration name" bind:value={integrationName}/><select bind:value={integrationKind}><option>github</option><option>jira</option><option>webhook</option><option>cron</option><option>mcp</option></select><select bind:value={integrationPlaybook}>{#each templates.filter(t=>t.role_type==='triage') as t}<option value={t.external_id}>{t.name}</option>{/each}</select><textarea bind:value={integrationConfig}></textarea><button on:click={()=>act(()=>saveIntakeConfig({name:integrationName,kind:integrationKind,enabled:true,playbook_id:integrationPlaybook,config:JSON.parse(integrationConfig)}))}>Add configuration</button>{#each configs as c}<article><strong>{c.name}</strong><span>{c.kind} · {c.enabled?'enabled':'disabled'} · {c.playbook_id}</span></article>{/each}<h3>Invite user</h3><input type="email" placeholder="analyst@example.com" bind:value={email}/><select bind:value={role}><option>admin</option><option>analyst</option><option>read-only</option></select><button on:click={()=>act(()=>inviteUser(email,role))}>Email invitation</button>{#each users as u}<article><strong>{u.email}</strong><span>{u.role} · {u.active?'active':'disabled'}</span><button on:click={()=>act(()=>updateUser(u.id,u.role,!u.active))}>{u.active?'Disable':'Enable'}</button></article>{/each}{:else}<p>Administration settings require the admin role.</p>{/if}{/if}</aside>{/if}
<style>.toggle{position:fixed;right:145px;top:8px;z-index:31;background:#243a55;color:#fff;border:0;border-radius:7px;padding:6px 10px}.toggle,button{cursor:pointer}aside{position:fixed;z-index:29;right:0;top:0;width:min(430px,95vw);height:100vh;overflow:auto;background:#0d1826;color:#e8eef8;padding:52px 20px 24px;box-shadow:-8px 0 30px #0008;font:13px system-ui}nav{display:flex;gap:5px;flex-wrap:wrap}nav button,.active{background:#243a55;color:#fff;border:0;padding:7px;border-radius:5px}.active{background:#567fbd}h2{margin-top:24px}input,select,textarea{box-sizing:border-box;width:100%;margin:5px 0;padding:8px;background:#08121e;color:#eef;border:1px solid #344b66;border-radius:5px}textarea{min-height:100px}article{display:grid;gap:5px;border:1px solid #263a50;padding:10px;margin:8px 0;border-radius:7px}article span{color:#9eb1c7}article button,aside>button{width:max-content;padding:6px 9px}.error{color:#ff9292}.ok{color:#75dc9a}dl{display:grid;grid-template-columns:1fr 1fr}pre{white-space:pre-wrap;word-break:break-word}</style>
