import assert from 'node:assert/strict';
const base=process.env.POCKETBASE_URL;
async function api(path,token,body,method=body===undefined?'GET':'POST',expected=200){
 const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const data=await response.json();assert.equal(response.status,expected,`${path}: ${JSON.stringify(data)}`);return data;
}
const auth=async(collection,identity,password)=>api(`/api/collections/${collection}/auth-with-password`,null,{identity,password});
const admin=(await auth('users','admin','asoc-smoke-password-2026')).token;
const root=(await auth('_superusers','smoke@asoc.local','asoc-smoke-superuser-password')).token;
const service=(await auth('services','runner@asoc.local',process.env.ASOC_RUNNER_PASSWORD)).token;
const create=(collection,data)=>api(`/api/collections/${collection}/records`,root,data);
const analyst=await create('users',{email:'authoring-analyst@asoc.local',password:'authoring-test-password',passwordConfirm:'authoring-test-password',role:'analyst',active:true,verified:true});
const reader=await create('users',{email:'authoring-reader@asoc.local',password:'authoring-test-password',passwordConfirm:'authoring-test-password',role:'read-only',active:true,verified:true});
const analystToken=(await auth('users',analyst.email,'authoring-test-password')).token;
const readerToken=(await auth('users',reader.email,'authoring-test-password')).token;
await api('/api/asoc/authoring/context',analystToken,undefined,'GET',403);
await api('/api/asoc/integrations',readerToken,undefined,'GET',403);
const unsafe=await create('intake_configs',{name:'Context redaction test',kind:'mcp',playbook_id:'TPL-TRIAGE',enabled:false,config:{url:'https://user:private-password@example.com/mcp?token=private-query',api_key:'hidden-api-value',token_env:'MY_MCP_TOKEN'}});
const ctx=await api('/api/asoc/authoring/context',admin);
for(const secret of ['private-password','private-query','hidden-api-value'])assert(!JSON.stringify(ctx).includes(secret));
assert(ctx.connections.some(c=>c.config.token_env==='MY_MCP_TOKEN'));
await api('/api/asoc/integrations',admin,{name:'Unsafe',kind:'mcp',enabled:false,config:{url:'https://example.com/mcp',token:'literal-secret'}},'POST',400);
const integration=await api('/api/asoc/integrations',admin,{name:'Safe MCP',kind:'mcp',enabled:false,config:{url:'https://example.com/mcp',token_env:'MY_MCP_TOKEN'}});
assert(integration.created_by);assert(integration.created);
await api(`/api/asoc/integrations/${integration.id}/discovery`,service,{status:'available',tools:[{name:integration.id+'.search'},{name:'forged.tool'}]});
const discovery=(await api('/api/asoc/integrations',admin)).find(c=>c.id===integration.id);assert.equal(discovery.tools.length,1);
const draft={title:'Reviewable resource',category:'skills',instructions:'# Résumé שלום\n\nInvestigate evidence.'};
let saved=await api('/api/asoc/authoring/save',admin,{kind:'resource',draft});
assert(saved.record.created_by);assert(saved.base_revision);
const fileToken=await api('/api/files/token',admin,{});
const file=await fetch(`${base}/api/files/resources/${saved.record.id}/${saved.record.body_md_file}?token=${fileToken.token}`);assert.equal(await file.text(),draft.instructions);
await api('/api/asoc/authoring/save',admin,{kind:'resource',draft,target_id:saved.record.id,base_revision:'stale'},'POST',400);
await api('/api/asoc/authoring/save',analystToken,{kind:'resource',draft},'POST',403);
const playbook={title:'Structured playbook',definition:{schema_version:1,name:'Structured playbook',role:'analysis',instructions:'Review evidence.',required_context:[],outputs:['markdown'],mcp_tool_policy:{},max_runtime_sec:60}};
const pb=await api('/api/asoc/authoring/save',admin,{kind:'playbook',draft:playbook});assert.equal(pb.record.version,1);
await api('/api/asoc/authoring/validate',admin,{kind:'playbook',draft:{...playbook,definition:{...playbook.definition,mcp_tool_policy:{'unknown.tool':'allow'}}}},'POST',400);
async function finish(request,draft){await api(`/api/asoc/tasks/${request.task_id}/claim`,service,{});await api(`/api/asoc/tasks/${request.task_id}/progress`,service,{status:'succeeded',result_summary_json:{markdown:JSON.stringify({explanation:'Test proposal',draft})}});}
const request=await api('/api/asoc/authoring/drafts',admin,{kind:'resource',target_id:saved.record.id,prompt:'Improve this',draft});
await finish(request,{...draft,instructions:'Changed proposal'});
const result=await api(`/api/asoc/authoring/drafts/${request.id}`,admin);assert.equal(result.proposal.draft.instructions,'Changed proposal');
const unchanged=await api(`/api/collections/resources/records/${saved.record.id}`,admin);assert.equal(unchanged.body_md_file,saved.record.body_md_file);
await api(`/api/asoc/authoring/drafts/${request.id}`,analystToken,undefined,'GET',403);
await api(`/api/collections/tasks/records/${request.task_id}`,readerToken,undefined,'GET',404);
const privateArtifact=await create('artifacts',{task_id:request.task_id,kind:'result',content:{private:'authoring draft'}});
await api(`/api/collections/artifacts/records/${privateArtifact.id}`,readerToken,undefined,'GET',404);
const incident=await create('incidents',{external_id:'INC-AUTHORING-TEST',title:'Restricted incident',severity:'SEV1',status:'open',visibility:'restricted',allowed_user_ids:[analyst.id]});
const sectionForm=new FormData();for(const [key,value] of Object.entries({external_id:incident.external_id+'/overview',incident_id:incident.external_id,section:'overview',title:'Overview'}))sectionForm.set(key,value);sectionForm.set('content_md_file',new Blob(['Original overview']),'overview.md');
const sectionResponse=await fetch(base+'/api/collections/incident_sections/records',{method:'POST',headers:{Authorization:root},body:sectionForm});assert.equal(sectionResponse.status,200);const section=await sectionResponse.json();
await api('/api/asoc/authoring/drafts',readerToken,{kind:'overview',target_id:section.id,prompt:'Summarize'},'POST',403);
const overview=await api('/api/asoc/authoring/drafts',analystToken,{kind:'overview',target_id:section.id,prompt:'Summarize'});
await finish(overview,{markdown:'# Reviewed overview'});
await api(`/api/collections/tasks/records/${overview.task_id}`,analystToken);
const authorizedEvidence=await create('artifacts',{task_id:overview.task_id,kind:'evidence',content:{summary:'Authorized evidence'}});
await api(`/api/collections/artifacts/records/${authorizedEvidence.id}`,analystToken);
await api(`/api/collections/artifacts/records/${authorizedEvidence.id}`,readerToken,undefined,'GET',404);
assert.equal((await api(`/api/collections/incident_sections/records/${section.id}`,analystToken)).content_md_file,section.content_md_file);
const applied=await api(`/api/asoc/authoring/drafts/${overview.id}/apply`,analystToken,{});assert(applied.content_md_file);
await api(`/api/asoc/authoring/drafts/${overview.id}/apply`,analystToken,{},'POST',400);
const stale=await api('/api/asoc/authoring/drafts',analystToken,{kind:'overview',target_id:section.id,prompt:'Summarize again'});
const competing=await api('/api/asoc/authoring/drafts',analystToken,{kind:'overview',target_id:section.id,prompt:'Fresh draft'});
await finish(stale,{markdown:'Old candidate'});await finish(competing,{markdown:'New candidate'});
await api(`/api/asoc/authoring/drafts/${competing.id}/apply`,analystToken,{});
await api(`/api/asoc/authoring/drafts/${stale.id}/apply`,analystToken,{},'POST',400);
const revoked=await api('/api/asoc/authoring/drafts',analystToken,{kind:'overview',target_id:section.id,prompt:'Summarize'});
await api(`/api/asoc/tasks/${revoked.task_id}/claim`,service,{});
await api(`/api/collections/incidents/records/${incident.id}`,root,{allowed_user_ids:[]},'PATCH');
await api(`/api/asoc/authoring/drafts/${revoked.id}/runner-context`,service,{task_id:revoked.task_id},'POST',403);
await api(`/api/asoc/authoring/drafts/${stale.id}/apply`,analystToken,{},'POST',403);
await api(`/api/asoc/tasks/${stale.task_id}/cancel`,analystToken,{},'POST',403);
await api('/api/asoc/tasks',analystToken,{template_id:'TPL-PERIODIC',incident_id:incident.external_id},'POST',403);
await api(`/api/collections/incident_sections/records/${section.id}`,analystToken,{title:'Unauthorized edit'},'PATCH',404);
await api(`/api/collections/tasks/records/${stale.task_id}`,analystToken,undefined,'GET',404);
const evidence=await create('artifacts',{task_id:stale.task_id,kind:'evidence',content:{private:'restricted incident evidence'}});
await api(`/api/collections/artifacts/records/${evidence.id}`,analystToken,undefined,'GET',404);
const incidentDashboard=await api('/api/asoc/incidents/INC-1002/dashboard',admin,{instructions:'Show incident tasks.'});
const dashboardRecord=await api(`/api/collections/dashboards/records/${incidentDashboard.dashboard.id}`,root);
const dashboardTask=await api(`/api/asoc/tasks/${dashboardRecord.last_generation_task_id}/claim`,service,{});
const query=await api('/api/asoc/tools/request',service,{task_id:dashboardTask.id,call_key:'test-incident-tasks',tool:'asoc.dashboard_query',arguments:{metric:'incident_tasks'}});
await api(`/api/asoc/tools/${query.id}/start`,service,{});
const preview=await api(`/api/asoc/tools/${query.id}/builtin`,service,{});assert(Array.isArray(preview.results.preview));assert(preview.results.preview.length>0);
console.log('Authoring smoke passed: validation, Unicode files, secret-safe context, explicit apply, stale drafts, owner and incident access, artifact ACLs, and access revocation.');
